Seagate/cortx-rgw

src/rgw/CMakeLists.txt
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Always generate new motr fid for objects, even for the same
S3 objects. This way even the same S3 object can be concurrently
written to motr. But only one of them is stored, for the other one
the error is returned, according to S3 API spec.
Closes #5.

rgw/motr: fix concurrent obj puts

---

src/common/options/rgw.yaml.in
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

The watch-notify can be used to watch (monitor) any update on objects.
A notification is sent (to all rgw instances) by a notifier if an object
is changed, such as object size, object content etc. The notification sent
contains marker for a watcher to pick it up and it also includes required
information for the watcher to act accordingly.
This POC shows how to implement the watch-notify mechanism using FDMI as
messge passing, filtering and notifying. We also show its usage in object
metadata cache uses where it is used to inform object changes and takes
action on cache items.
Signed-off-by: Sining Wu <sining.wu@seagate.com>
<details>
<summary>Show available Jenkins …

rgw_sal_motr: implement watch-notify mechanism using Motr FDMI

---

src/rgw/rgw_sal_motr.cc

Currently, if the same object is written again, user gets
S3 error: 409 (BucketAlreadyExists).
Solution: 1) update the existing bucket index object record
instead of returning an error; 2) handle -EEXIST error when
creating multipart object index.

rgw_sal_motr: fix existing objects re-write

---

src/rgw/rgw_sal.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Currently, the MotrAtomicWriter::cleanup() is called from
MotrAtomicWriter::commit(), which may not be called at all
by rgw in case of md5 checksum failure.
Solution: call cleanup() from process() when data is zero.
rgw calls Writer::process(data, off) with zero data at the
end of the loop to allow writes to flush the data. From:
src/rgw/rgw_op.cc:RGWPutObj::execute():
op_ret = filter->process(std::move(data), ofs);
...
ofs += len;
} while (len > 0);
// flush any data in filters
op_ret = filter->process({}, ofs);
Closes #70.

rgw_sal_motr: fix possible memleak on put

---

src/common/options/rgw.yaml.in
src/rgw/rgw_admin.cc
src/rgw/rgw_sal_motr.cc

EOS-28049: Fix for Radosgw admin tool with motr 

---

src/rgw/rgw_sal_motr.cc

While destructing MotrStore object, close connection with motr.
<details>
</details>

Close connection with Motr

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
Added the default zone group api_name and id, so that each new bucket will have zonegroup_id in its metadata, and get_location API will return the zone group of a particular bucket.
```bash
->  aws s3api create-bucket \                                                         
--bucket my-bucket2 \
--region default \
--create-bucket-configuration LocationConstraint=default \
--endpoint=http://localhost:8000
->  aws s3api create-bucket \                 
--bucket my-bucket2 \
--region default1 \
--create-bucket-configuration LocationConstraint=default1 \
--endpoint=http://localhost:8000
An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
->  aws …
```

rgw_sal_motr: [EOS-27563] Initiate default values for Zonegroup

---

src/common/options/rgw.yaml.in
src/rgw/rgw_sal_motr.cc

Rename it so that all motr parameters start with `motr_` prefix.

rgw_sal_motr: rename admin_motr to motr_admin

---

src/rgw/rgw_sal_motr.cc

**Parent Ticket:** [CORTX-27526](https://jts.seagate.com/browse/CORTX-27526)
**Problem statement:** Incorrect LastModified Date in GetObj API.
```bash 
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹main*›
╰─➤  aws s3api get-object --bucket my-bkt --key output.file stdout                                                      2 ↵
{
"AcceptRanges": "bytes",
"LastModified": "Thu, 01 Jan 1970 00:00:00 GMT",
"ContentLength": 1048576,
"ETag": "\"b6d81b360a5672d80c27430f39153e2c\"",
"ContentType": "binary/octet-stream",
"Metadata": {}
}
```
**Problem Analysis & Solution:**
In `RGWGetObj::execute()` method `MotrReadOp read_op` obj is created.
`read_op->prepare()` is supposed to set the `lastmod` time for this object,
which is missing in `MotrReadOp::prepare()` method, …

rgw_sal_motr: [CORTX-28690] Fix for incorrect LastModified time in GetObj API

---

src/rgw/rgw_sal_motr.cc

_[CORTX-27650](https://jts.seagate.com/browse/CORTX-27650):_
_Fix create bucket API issues with ceph and splunk test suite._
_[CORTX-28758](https://jts.seagate.com/browse/CORTX-28758):_
_Fix Remaining create bucket tests._
N/A
1. If get_bucket returns ENOENT, then create bucket.
2. If get_bucket returns 0, then send -EEXIST error.
<details>
<summary> **Case 1 : Create Bucket with same name** </summary>
> [root@ssc-vm-g4-rhev4-0344 build]# s3cmd --no-ssl mb s3://testbucket3
> ERROR: Bucket 'testbucket3' already exists
> ERROR: S3 error: 409 (BucketAlreadyExists)
</details>
<details>
<summary> **Ceph Tests V4** </summary>
> (virtualenv) [root@ssc-vm-g4-rhev4-0344 s3-tests]# S3TEST_CONF=./s3tests.conf ./virtualenv/bin/nosetests s3tests_boto3.functional.test_s3:test_bucket_create_delete -vv …

rgw_sal_motr: [CORTX-27650] Creating bucket with same name does not fail

---

src/rgw/rgw_sal_motr.cc

…ackend.
Signed-off-by: Diwakar92 <diwakar.kumar@seagate.com>
<details>
</details>

CORTX-28052: Create User for same UID with different Tenant

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

[CORTX-27516](https://jts.seagate.com/browse/CORTX-27516):
_PutObject API in RGW+Motr_
[CORTX-28765](https://jts.seagate.com/browse/CORTX-28765) - _Handle object overwrite_
**Changes:** Initialing existing object before creating new object. Once new objects is written successfully, deleting previous object's data in motr.
[CORTX-28776](https://jts.seagate.com/browse/CORTX-28776) - _Verify Parallel uploads_
**Changes:** Found object leak during parallel upload which we will be properly design and fixed in Jira : [CORTX-28825](https://jts.seagate.com/browse/CORTX-28825). For now, added a TODO comment in the code.
<details><summary>Overwrite object</summary>
> [root@ssc-vm-g4-rhev4-0499 ~]# md5sum testfile
> 8e5daee75e9a4bb3d912168d5c14f960  testfile
> [root@ssc-vm-g4-rhev4-0499 ~]# aws …

rgw_sal_motr: [EOS-27516] Handling object overwrite during put-object

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Parent Ticket: https://jts.seagate.com/browse/CORTX-27526
Adding support for
1. [--if-match <value>]
2. [--if-modified-since <value>]
3. [--if-none-match <value>]
4. [--if-unmodified-since <value>]
The output of all 8 possible scenarios is captured [here](https://jts.seagate.com/browse/CORTX-27526).
<details>
<summary> --if-match </summary>
<br>
```bash
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹main*›
╰─➤  aws s3 ls my-bkt/obj1
2022-02-14 04:14:08    1048576 obj1
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹main*›
╰─➤  aws s3api get-object --bucket my-bkt --key obj1 --if-match b6d81b360a5672d80c27430f39153e2c ~/downloded.file
{
"AcceptRanges": "bytes",
"LastModified": "Mon, 14 Feb 2022 11:14:08 GMT",
"ContentLength": 1048576,
"ETag": …
```

rgw_sal_motr: [CORTX-28693] Conditional Param support for GetObj

---

src/rgw/rgw_sal_motr.cc

**Bug:** https://jts.seagate.com/browse/CORTX-28960, get of zero-byte objects fails with NoSuchKey error.
GET-Object operation is successful for non-zero size objects . Issue seen only with zero size object.
Console output Logs :
```bash
[root@ssc-vm-g4-rhev4-0935 ~]# touch abc.txt
[root@ssc-vm-g4-rhev4-0935 ~]# aws s3 cp abc.txt s3://bkt --endpoint http://localhost:8000
upload: ./abc.txt to s3://bkt/abc.txt
[root@ssc-vm-g4-rhev4-0935 ~]#
[root@ssc-vm-g4-rhev4-0935 ~]# aws s3api get-object --bucket bkt --key abc.txt abcout.txt --endpoint http://localhost:8000
An error occurred (NoSuchKey) when calling the GetObject operation: Unknown
```
**Bug Analysis:** 
In open_mobj we have a following check
```c++
if (meta.layout_id == 0)
return -ENOENT;
```
This check for zero-byte objects results in …

rgw_sal_motr: [CORTX-28960] fix for get zero-byte obj failure.

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

[CORTX-28060](https://jts.seagate.com/browse/CORTX-28060)
Implementation of deletion of a specified access key for a user who owns multiple access keys.
N/A
Access keys are stored in user info as well as in access key index table. `access_key_tracker` keeps track of access keys of current user. When key deletion is requested, RGW code takes care of deleting the specified key from user info. This creates a mismatch between access keys in user info and access keys tracked by `access_key_tracker` which triggers key deletion from access key index table. 
Following command is enabled:
```
radosgw-admin key rm <access-key>
``` …

rgw_sal_motr: [CORTX-28060] Delete access key for an IAM user

---

src/rgw/rgw_sal_motr.cc

- https://jts.seagate.com/browse/CORTX-27528
- https://jts.seagate.com/browse/CORTX-29114
**Problem:** 
- MotrDeleteOp::delete_obj api was trying to delete the object without opening it first because of that mobj was not initialized with the object oid.
- Deleting an zero size object fails while deleting motr object.
**Fix:** 
- Doing a get_bucket_dir_ent() on object before trying to delete it, it will do a lookup on object and initialize it as well.
- Checking object size before trying delete the motr object.
<details><summary> Test 1: </summary>
>[root@ssc-vm-g4-rhev4-0499 ~]# aws s3 ls s3://buck
>2022-02-24 05:47:46   16778808 large
>2022-02-24 05:45:29   10227542 small
>2022-02-23 03:27:29   10210440 vmlinux
>2022-02-27 22:35:33 …

rgw_sal_motr: [CORTX-27528] Fixing issue with delete object.

---

src/rgw/rgw_sal_motr.cc

Get object for s3cmd is giving checksum mismatch warning during getting the data from s3.
[root@ssc-vm-g3-rhev4-2880 ~]# s3cmd --no-ssl get s3://testbucket3/vmlinux vmlinux
download: 's3://testbucket3/vmlinux' -> 'vmlinux' [1 of 1]
10210440 of 10210440 100% in 0s 134.52 MB/s done
WARNING: MD5 signatures do not match: computed=92326b2cc6b6898b4c3f238dff8c0b10, received=f9c5cc6840ab0093475b3b0699f4e58b
Bl is initialized in every iteration. So the new data is stored from the 0th index every time in bl. But in code we are passing 'off' to handle_data function. This is result in writing from different index and result in checksum mismatch, we have to pass 0 in place of off in handle_data function …

rgw_sal_motr:[CORTX-27698] Checksum mismatch for GET API

---

src/rgw/rgw_sal_motr.cc

Issue Fixes:
1. RGW crashes when a delimiter is used with max-keys. (in a specific scenario)
<details><summary>Issue observation</summary></br>
```bash
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹CORTX-29094-fixListObjParams*›
╰─➤  aws s3api list-objects-v2 --bucket mybkt --max-keys 3 --delimiter /  --continuation-token output.file
Could not connect to the endpoint URL: "http://localhost:8000/mybkt?list-type=2&delimiter=%2F&max-keys=3&continuation-token=output.file&encoding-type=url"
```
Logs:
```bash
1137  20 req 0 0.007000023s s3:list_bucket bucket=mybkt prefix= marker=output.file max=     3
1138  20 id = 0xd45ec53807bb2c24:0x8786bc02fd5ae88e
1139  20 converted id = 0x7800000007bb2c24:0x8786bc02fd5ae88e
1140  20 next_query_by_name: next_query_by_name(): …
```

rgw_sal_motr: [CORTX-29094] Improve ListObjs / ListObjsV2 API

---

src/rgw/rgw_sal_motr.cc

**Problem :** If version id parameter is passed as null to delete-object
API in case of unversioned bucket for deletion of simple object,
then object deletion does not happen.
**Implementation :** If instance is set to "null" we clear this string
in delete_object implementation. This implementation is similar to
what is done in rados.
_[CORTX-28987](https://jts.seagate.com/browse/CORTX-28987):_
_Deletion of simple object with null version id._
NA
Multipart object not tested.
<details>
<summary> **Case 1 : Deleting Simple Object in unversioned bucket** </summary>
> [root@ssc-vm-g4-rhev4-0344 build]# aws s3 mb s3://unversionedtestbucket --endpoint-url http://127.0.0.1:8000
> make_bucket: unversionedtestbucket
> [root@ssc-vm-g4-rhev4-0344 build]# aws s3 cp 1mfile s3://unversionedtestbucket …

rgw_sal_motr: [CORTX-28987] Fix object deletion with null version

---

src/rgw/rgw_sal_motr.cc

Problem:
When Multipart ListParts API is invoked using aws s3api command with invalid values for parameters like, max-items, page-size, max-parts, inconsistent results are displayed to the end user. The issue is parameter validation (check for -ve and zero value was not in place).
Resolution:
Added code to handle negative and zero values to the parameters in "aws s3api list-parts" command line.  This should avoid RGW application crash.
_[CORTX-29221](https://jts.seagate.com/browse/CORTX-29221):_
_Multipart Part Listing API negative/corner cases handling_
NA
NA.
Added code to handle 0 and -ve value checking of parameters in aws s3api list-parts command.
<details>
<summary> **Case 1 : Invoke aws s3api list-parts with max-parts 0 and negative values** </summary>
The response is consistent …

rgw_sal_motr: [CORTX-29221] Fix corner/negative cases in Multipart ListParts API

---

src/rgw/rgw_sal_motr.cc

**Bug:** https://jts.seagate.com/browse/CORTX-29411
**Problem & RCA:** 
* In ListParts API we are validating for `curr_part_number == prev_part_number + 1`.
* If we have uploaded parts 1 and 10000, then the List Part API errors out as the part numbers are not consecutive.
This is not an expected behaviour.
**Solution:** 
* `expected_next` part number is used in Rados to differentiate between sorted and unsorted keys. If the keys are not consecutive then the gateway does not support sorted_omap. 
* Motr KVS on the other hand has all the keys sorted and there is no effect of non-consecutive keys on reading them.
* so there seems no need to keep track of the `expected_next` variable
* Removing the code related to `expected_next` variable.
- …

rgw_sal_motr: [CORTX-29411] Fix ListParts API for non-consecutive parts

---

src/rgw/rgw_sal_motr.cc

If we are giving byte range from 0 to any random number then get object is working, but if we are giving the range from non zero value then get object api is not working. Giving error "No Such Key"
In normal get object API, motr reads in block size, here in diagram suppose our object is being divided into 6 blocks, motr will start reading from 0th offset and reads block by block and pass it to the client.
Now take an example of byte range:-
Suppose the starting offset is present in block 1 and end offset is present in block4.  We have to to send the data from particular offset,  first we have to read the whole block and once we get the whole block from the motr we will pass the data from particular offset to the client. …

rgw_sal_motr:[CORTX-29171] Fixed byte range issue in get object api

---

src/rgw/rgw_sal_motr.cc

Problem:
Due to invalid/junk values of pv id and layout type in some index operations (due to uninitialized variable of type struct m0_idx), lib Motr raises assert, causing rgw server to crash. 
Resolution:
The fix initializes "struct m0_idx idx", so that pv id and layout type are set to 0 during lib Motr index operations.
<details> …

rgw_sal_motr: [CORTX-29534] Fix rgw server crash due to lib Motr assert

---

src/rgw/rgw_sal_motr.h

There are many memory leaks reported in rgw server by valgrind. It points to the memory allcations done in MotrZone class, that is not released in the destructor.
```
==3606169== 176 bytes in 1 blocks are indirectly lost in loss record 27 of 53
==3606169==    at 0x4C36B6F: operator new[](unsigned long) (vg_replace_malloc.c:640)
==3606169==    by 0x552719C: allocate (new_allocator.h:111)
==3606169==    by 0x552719C: allocate (alloc_traits.h:436)
==3606169==    by 0x552719C: _M_get_node (stl_tree.h:588)
==3606169==    by 0x552719C: _M_create_node<const std::piecewise_construct_t&, std::tuple<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>, std::tuple<> >
(stl_tree.h:642)
==3606169==    by 0x552719C: …
```

rgw_sal_motr: [CORTX-29526] fix memleaks in MotrZone

---

src/rgw/rgw_sal_motr.cc

Ticket: https://jts.seagate.com/browse/CORTX-29664
Problem Description:
- For a head object s3api, there is no need to open an object since only metadata and no body is returned.
for more info on head object, s3api refer : https://docs.aws.amazon.com/cli/latest/reference/s3api/head-object.html
- while doing a head object s3API call, the object was getting opened in MotrObject::MotrReadOp::prepare() which was not needed at all.
- also, we were not closing the object which might result in a memory leak.
Problem Solution:
- The solution is to open the object in MotrObject::MotrReadOp::iterate() instead of prepare().(we don't come until iterate in head-object s3api call)
- This won't call open_mobj() unnecessarily during head-object s3api call.
Signed-off-by: Pranav Diliprao Pawar …

rgw_sal_motr: [CORTX-29664] optimise head-object s3api handling

---

src/rgw/rgw_admin.cc
src/rgw/rgw_sal.h
src/rgw/rgw_sal_dbstore.cc
src/rgw/rgw_sal_dbstore.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h
src/rgw/rgw_sal_rados.cc
src/rgw/rgw_sal_rados.h
src/rgw/rgw_user.cc

[CORTX-28064](https://jts.seagate.com/browse/CORTX-28064)
Function for user list api are called directly from `rgw_admin.cc` (in case of CLI) and from `rgw_user.cc` (in case of REST API). These functions are closely integrated with rados which makes implementation of user list complex for other stores.
Move function calls for user list to backend store. 
A new function `list_users()` is introduced in backend store which will call the `meta_list_keys_init()`, `meta_list_keys_next()` and `meta_list_keys_complete()` functions for rados as backend. 
Other stores can independently implement `list_users()` function without following implementation of above 3 functions. 
<details>
<summary>CLI</summary>
<pre>
$ bin/radosgw-admin user list …

rgw: [CORTX-28064] Enable store specific implementation for user list

---

src/rgw/rgw_rest_user.cc

**Problem** : Adding access key to existing user not reflecting to correct user/tenant
**Root Cause**: tenant name is not being populated while adding access key operation.
**Solution** : added fix for populating tenant name during the execution
of access key creation.
**Jira Associated**: https://jts.seagate.com/browse/CORTX-29398
Signed-off-by: sanalpk [sanal.kaarthikeyan@seagate.com](mailto:sanal.kaarthikeyan@seagate.com)
<details>
- `jenkins …

rgw: [CORTX-29398] Fix for adding access key to existing user issue

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

**Problem**:
1. Incorrect object part layout id
During Motr part object creation, rgw_max_chunk_size (default=4MB in ./rgw.yaml.in) is passed to compute object layout id(lid), and not the actual object part's size. The actual part size is available from Content-Length header. Due to this, incorrect lid is set on the created part object.
2. Additional data is seen added to object storage due to padding. 
This increases the bytecount of some objects in storage.
**Resolution**:
For (1):
Determine the part object size using Content-Length header value. Pass the same during part object creation using Motr.
For (2): 
Apply padding only to the last IO chunk read from the client. For  intermediate chunks, accumulate them in an internal list,  until complete data is read from the client. Then …

rgw_sal_motr: [CORTX-29655] Fix bytecount for multipart object sizes

---

src/rgw/rgw_sal_motr.cc

rgw_sal_motr: [CORTX-27629] Fix for page-size parameter in list multiparts upload api
**Problem** - 
1)List multipart api parameter page-size was not working as expected, for page-size 0 and less then 0 rgw was crashing
2) For page size 1, it was giving error. And for greater than page-size 1 , it was listing duplicates upload id on console.
**Solution**  Added a check for page size less then equal to 0, so that we can return 0 from starting of function. 
For page size 1 and more than 1 added a condition such that if marker is not empty then we have to skip that upload id to copy to vector to avoid duplicates as that id is already being present in result vector.
> **1) For page size 0**
[root@ssc-vm-g4-rhev4-0761 build]# aws …

rgw_sal_motr: [CORTX-27629] Fix for page-size parameter in list multiparts upload api

---

src/rgw/rgw_process.cc
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

For motr as backend, get_new_req_id() always returns 0.
Also, request id is not correctly printed in the logs.
As part of debugging the defect [CORTX-30705](https://jts.seagate.com/browse/CORTX-30705), we observed that request ids for different requests are same.
Add code to generate unique request id for each new request.
Print `req->id` in logs instead of `req` (address of request object)
Multiple request: 
```
[root@ssc-vm-g4-rhev4-0499 cortx-rgw]# aws s3 ls
2022-03-30 03:59:11 buck
[root@ssc-vm-g4-rhev4-0499 cortx-rgw]# aws s3 ls
2022-03-30 03:59:11 buck
[root@ssc-vm-g4-rhev4-0499 cortx-rgw]# aws s3 ls
2022-03-30 03:59:11 buck
```
rgw logs:
```
2022-04-19T06:28:28.724-0600 7f6b3af25700  1 ====== starting new request …
```

rgw: [CORTX-30705] generate unique request id for motr backend

---

src/rgw/rgw_sal_motr.cc

Problem:
Unexpected EOF is seen while downloading large (e.g. 5GB) object.
This was due to incorrect variable type(unsigned int) chosen for storing
object size and offset. As the limit of unsigned int is 0 to 4294967296(4GB),
an overflow happened when 5GB is assigned to it. This overflow sets value of
~1GB in the variable, causing server to return only ~1GB data to client
during Get API, further causing unexpected EOF on client side.
Resolution:
Use higher order int variable type, say int64_t, to store object size
and other data offset values.
<details> …

rgw: [CORTX-29660] Fix unexpected EOF seen during download of large object

---

src/rgw/rgw_rest_user_policy.cc

GetUserPolicy & ListUserPolicies responses has few mistakes/typos when compared with aws documentation.
Due to this mistake, when `aws iam get-user-policy/list-user-policies` command is called it causes a blank/incorrect response.
```
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹main›
╰─➤  aws iam get-user-policy --endpoint-url http://localhost:8000 --user-name mgwuser --policy-name putBktDeny
╭─root@ssc-vm-g4-rhev4-0318.colo.seagate.com ~/cortx/cortx-rgw/build  ‹main›
```
```
╰─➤  aws iam list-user-policies --endpoint-url http://localhost:8000 --user-name mgwuser
...
{2022-04-27 23:13:24,641 - MainThread - botocore.parsers - DEBUG - Response body:
b'<ListUserPoliciesResponse><ResponseMetadata><RequestId></RequestId></ResponseMetadata><ListUserPoliciesResult><Poli …
```

rgw_rest_user_policy: [CORTX-31006] Fix Get & List User Policy responses

---

src/rgw/rgw_op.cc
src/rgw/rgw_sal_motr.cc

Handle deletion of old object during object overwrite situation, while executing Complete multipart API.
<details>
</details>

rgw_sal_motr: [CORTX-27628] Support Multipart Complete API in RGW

---

src/rgw/rgw_usage.cc

Problem : Storage stats for a user was not there as part of usage API.
Solution : Updated stats for a user and added those fields as part of usage API.
Signed-off-by: Diwakar92 <diwakar.kumar@seagate.com>
<details>
</details>

rgw_usage:CORTX-30360: Added Storage Stats as part of usage API to get capacity used by a user.

---

src/rgw/rgw_sal_motr.cc

Problem:
PutBucketTagging API didn't work with motr as backend. It throws BucketAlreadyExists error while trying to set tags for a bucket
Resolution:
Slight modifications has been done in sal_motr code to enable the API.
Based on exclusive(boolean), it sets flags as M0_OIF_OVERWRITE which resolves BucketAlreadyExists error
```
M0_OIF_OVERWRITE -->For M0_IC_PUT operation, instructs it to silently overwrite existing record with the same key, if any
```
Results:
```
[root@ssc-vm-g2-rhev4-3138 ~]# aws --endpoint=$endpoint s3api put-bucket-tagging --bucket test-buckets --tagging '{"TagSet":[{ "Key": "team", "Value": "c5-solvers" }]}'
[root@ssc-vm-g2-rhev4-3138 ~]# aws --endpoint=$endpoint s3api get-bucket-tagging --bucket test-buckets                                {
"TagSet": [
{
"Key": …
```

rgw_sal_motr: [CORTX-30344]PutBucketTagging: Sets tags for a bucket

---

src/rgw/rgw_sal_motr.cc

Problem:
PutObjectTagging API didn't work with motr as backend. No implementation found for set_obj_attrs method 
Resolution:
Added a block of code to set the object attributes in sal_motr code to enable the API.
Results:
```
[root@ssc-vm-rhev4-2587 ~]# aws --endpoint=$endpoint s3api put-object-tagging --bucket test-obj-buckets6 --key test-key-01 --tagging '{"TagSet": [{ "Key": "designation", "Value": "confidentials" }]}'
[root@ssc-vm-rhev4-2587 ~]# aws --endpoint=$endpoint s3api get-object-tagging --bucket test-obj-buckets6 --key test-key-01           {
"TagSet": [
{
"Key": "designation",
"Value": "confidentials"
}
]
}
```
- Tests (select at least …

rgw_sal_motr: [CORTX-30348] PutObjectTagging: Set tags for an object

---

src/rgw/rgw_sal_motr.cc

Problem:
Object's size on backend Motr storage shows more space than expected in a given
storage configuration. This was due to padding done to align data to the group size.
Resolution:
The padding done to the last IO in data alignment can be minimized further by aligning data to
the unit size boundary, instead of group size. The unit size aligned padding
requires the use of RMW flag from Motr backend storage to indicate no RMW
operation  when number of units available are less than the group size.
<details> …

rgw_sal_motr: [CORTX-29962] Optimise object storage size

---

src/rgw/rgw_op.cc

Problem:
Referring to https://docs.aws.amazon.com/cli/latest/reference/s3api/complete-multipart-upload.html, the Etag value in the response of Complete API was not formatted correctly. E.g., 
"ETag": "\\"3944a9f7a4faab7f78788ff6210f63f0-3\\""
Resolution:
Enclosed original/calculated Etag string within double quotes (as expected in AWS S3 standard).
<details> …

rgw_op: [CORTX-31065] Fix Etag in Complete API response

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem :
Current Multipart uploads had part details in an index named
"motr.rgw.object." + tenant_bkt_name + "." + oid + "." +  ".parts".
Due to this behavior 2 Multipart uploads for same object would
share same table and list each others parts, and may lead to corrupted data
Solution :
Changed the current implementation by appending upload_id
to the index name. This creates seperate index table for
each upload id where all parts related to that upload id
would be present.
<details>
<summary>Testing</summary>
> [root@ssc-vm-g4-rhev4-0344 build]# aws s3api create-multipart-upload --bucket testbucket1 --key dmultipartup2 --endpoint-url http://127.0.0.1:8000
> {
>     "Bucket": "testbucket1",
>     "Key": "dmultipartup2",
>     "UploadId": "2~ZsW30EjwvJb0jgTNvffovl6FCeUGBL6"
> }
> …

rgw_sal_motr: [CORTX-29112] Fix list-parts api for parallel multipart uploads.

---

src/rgw/rgw_sal_motr.cc

Currently, if there is an error on object metadata dix put
operation at the end of object PUT operation - the written
motr object data is not cleaned up and is leaked.
Solution: cleanup motr object on metadata put error.
Also, don't delete the old object if the new object put has failed.
<details>
- `jenkins render …

rgw_sal_motr: fix data leak on put error

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

`MotrStore::open_idx()` is not used - drop it.
<details>
</details>

rgw_sal_motr: drop obsolete open_idx()

---

src/rgw/rgw_sal_motr.cc

**Problem:-** list-multipart-upload api parameter max-upload and prefix are not working as expected.
**Fix:**- One condition was not added for max-uploads parameter, because of that it was listing one more upload, added the condition such that it should list according to the given input. 
For prefix parameter we were comparing the wrong data source in code, so changed with correct data source so that can list all the parameters according to the prefix.
**Test results**
1)
[root@ssc-vm-g4-rhev4-0761 ~]# aws s3api list-multipart-uploads --bucket testbucket3  --prefix "ab"
{
"Uploads": [
{
"UploadId": "2~FEM8fSC_H7llkOMiTVTG8ru-Sxq0WHn",
"Key": "ab",
"Initiated": "2022-05-02T05:35:38.426Z",
"StorageClass": "STANDARD",
"Owner": { …

rgw_sal_motr: [CORTX-30790] Fix for max-uploads and prefix parameter in list multipart upload api

---

src/rgw/rgw_rest_bucket.cc

`max-size` attr is not supported for SetBucketQuota as that of SetUserQuota.
Adding support for the attribute, keeping the `max-size-kb` as dominating in case
both are mentioned.
```bash
Wed, 4 May 2022 08:57:08 GMT
/admin/bucket
PUT http://ssc-vm-g4-rhev4-0318.colo.seagate.com:8000/admin/bucket?quota&bucket=mybkt&uid=mgwuser&max-size=990927 HTTP/1.1
Auth: AWS NB71GXG3O7MMBELODQOO:dCokdTJdD2C55V58gjndOmUGC20=
HTTP/1.1 200 OK
Response Content is:
```
```bash
Wed, 4 May 2022 08:57:27 GMT
/admin/bucket
GET http://ssc-vm-g4-rhev4-0318.colo.seagate.com:8000/admin/bucket?stats&bucket=mybkt&uid=mgwuser HTTP/1.1
Auth: AWS NB71GXG3O7MMBELODQOO:2A7il8HXIwz+WgV7aBJ4rDKTefY=
HTTP/1.1 200 OK
Response Content is: [{"bucket":"mybkt","num_shards":1,"tenant":"","zonegroup":"0956b174-fe14-4f97-8b50-bb7ec5e1 …
```

rgw_rest_bucket: [CORTX-31085] Support `max-size` attr for SetBucketQuota

---

src/rgw/rgw_sal_motr.cc

Reverting commits related to object tagging. These changes are affecting bucket metadata operations.
Below PRs are reverted:
https://github.com/Seagate/cortx-rgw/pull/186
https://github.com/Seagate/cortx-rgw/pull/172
<details> …

rgw-sal-motr:[CORTX-31313] Fix for bucket metadata update ops

---

src/rgw/rgw_sal_motr.cc

Problem:
Enabled PutBucketTagging API by removing negation in exclusive flag(#172 ). PutBucketVersioning API is affected due to this change. 
1. CreateBucket initially calls put_info() where exclusive=true, hence update=False.
2. PutBucketTagging calls put_info() where exclusive=false to make update=True. If PutBucketTagging is called with exclusive=True, it will try to CreateBucket again as mentioned in step 1
Resolution:
By setting exclusive to false in put_info() function updates the attributes and  resolves the issue
Results:
```
[root@ssc-vm-rhev4-2587 build]# aws --endpoint=$endpoint_url s3api put-bucket-versioning --bucket test-buckets --versioning-configura Status=Suspended
[root@ssc-vm-rhev4-2587 build]# aws …
```

rgw_sal_motr: [CORTX-31196]PutBucketTagging: Call put_info() with false to update the attributes

---

.github/workflows/dispatch_submodule_update.yml

**Problem :** 
Commit hash of cortx-rgw is static at cortx repository and has to be updated manually which is quite tedious to do for every commit.
**Solution :**
Added the Github action workflow which will dispatch the event with latest commit hash of cortx-rgw to parent cortx repo.
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
<details>
- `jenkins …

CORTX-30632: Added the submodule dispatch event

---

src/rgw/rgw_admin.cc
src/rgw/rgw_sal_motr.cc

list user api was returning all users if a non-existing marker is supplied with the request. This issue is fixed by adding a check whether the supplied marker exists or not.
<details> …

rgw: [CORTX-28065] fix issues with non-existing marker in list user api

---

src/rgw/rgw_sal_motr.cc

Problem description:
- Head object and Get object with version-id attribute is giving latest version contents always in the response. 
Solution:
- Adding the conditions in the `get_bucket_dir_entry()` method to get the object contents of specific version.
During testing, some cache issues are observed in the head & get object API with specific version id. The Jira is created and added the observed cache issues there. - https://jts.seagate.com/browse/CORTX-31109. This code is tested with `rgw cache enabled = false` parameter. 
Head and Get object with null version-id cases will be covered in another PR - https://github.com/Seagate/cortx-rgw/pull/200
- Documentation (select at …

rgw_sal_motr : [CORTX-27638] : Fix for Head and Get object with version-id parameter

---

src/rgw/rgw_sal_motr.cc

Motr bucket delete attrs operations fix.
Problem: 
Since we entirely removing the tagset key from attrs. Merging new attrs and existing attrs won't work as expected for all bucket delete attribute operations. Because as per the existing logic if a key not present in newly passed attribute then the program will consider the existing key value pairs itself as final.
Fix posted:
Updated merge and store method logic of motr bucket by assigning the new bucket attrs parameter to mor bucket attrs variable.
Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>
<details>
- …

rgw_sal_motr : [CORTX-30347]: DeleteBucketTagging :  Fixed merge_and_save method to incorporate and update deleted attributes

---

src/rgw/rgw_sal_motr.cc

Problem :
Delimiter parameter not supported in multipart uploads.
For example the below query wont filter out multiparts begining
with test
aws s3api list-multipart-uploads --bucket multiparttable --delimiter test --endpoint-url http://127.0.0.1:8000
Solution :
Passed delimiter parameter to query api of motr.
changed the loop for evaluation of results.
Signed-off-by: Deepak Mahale <deepak.mahale@seagate.com>
<details>
<summary>Testing Done</summary>
> [root@ssc-vm-g4-rhev4-0344 build]#  aws s3api list-multipart-uploads --bucket multiparttable --endpoint-url http://127.0.0.1:8000
> {
>     "Uploads": [
>         {
>             "UploadId": "2~zo4vCNd1kt5gWqbL9XYdIgGmOYuLcKK",
>             "Key": "deep",
>             "Initiated": "2022-05-10T10:53:05.624Z",
>             "StorageClass": …

rgw_sal_motr: [CORTX-31087] Support delimiter parameter for multipart uploads.

---

src/rgw/rgw_sal_motr.cc

Problem:
The download of multipart object fails when the part size is not
multiple of 4MB.
Due to logical issue in code, during object write, the last IO chunk is written to
the already written offset; thereby causing less object size. 
When such object is read, it tries to read more data than available, 
causing Motr to return -ENOENT.
Solution:
Fixed logical issue in code so that last IO write is done in the correct
offset/region of object space.
<details>
- …

rgw_sal_motr: [CORTX-31066] Fix multipart object download

---

src/rgw/rgw_sal_motr.cc

Problem description:
1. Object versions listed in random order in List Object Versions API
2. is-latest flag is true for multiple versions if version-enabled bkt contains more than 30 versions of same object.
3. is-latest flag is true for null and previous latest versioned obj if bkt versioning status changed from version enabled to suspended.
Solution:
1. To resolve 1st two issue generated timestamp based version-ids.
2. To fix 3rd issue calling update_vesrion_entreis method in MotrAtomicWriter::complete fuc for both version suspended & enabled case.
<details> …

rgw_sal_motr: [CORTX-30178] Generate version-id based on timestamp

---

src/rgw/rgw_sal_motr.cc

Observed 2 issues with is-latest flag during list-object-versions API:
- is-latest flag set for two versions of the same object
- is-latest flag is not getting updated in list-object-versions API
Issues observed with is-latest flag:
```
[root@ssc-vm-rhev4-2551 ~]# aws --endpoint=http://10.230.249.130:8000 s3api list-object-versions --bucket test-bucket11
{"Versions": [
{ "ETag": ""f1c9645dbc14efddc7d8a322685f26eb"",
"Size": 10485760,
"StorageClass": "STANDARD",
"Key": "test-obj1",
"VersionId": "null",
"IsLatest": true,
"LastModified": "2022-05-11T08:42:56.117Z",
"Owner": 
{ "DisplayName": "test",
"ID": "test"
}
},
{"ETag": ""f1c9645dbc14efddc7d8a322685f26eb"","Size": 10485760,
"StorageClass": "STANDARD",
"Key": "test-obj1",
"VersionId": "zWuU7XGZHelDEVS06G23gS5y4C9dMhx",
"IsLatest": true, …
```

rgw_sal_motr : [CORTX-30180] Fix for is-latest flag issue

---

src/rgw/rgw_sal_motr.cc

Problem:
PutObjectTagging API is overwriting the metadata of an object since a new instance of rgw_bucket_dir_entry is created. 
Reference: https://github.com/Seagate/cortx-rgw/pull/186#discussion_r866815923
Resolution:
Make sure to just update the metadata, and avoid overwriting rgw_bucket_dir_entry
Results:
```
[root@ssc-vm-rhev4-2587 build]# aws --endpoint=$endpoint s3api put-object-tagging --bucket test-buckets2 --key test-key-111 --tagging '{"TagSet": [{ "Key": "project", "Value": "rgw" }]}'
[root@ssc-vm-rhev4-2587 build]# aws --endpoint=$endpoint s3api get-object --bucket test-buckets2 --key test-key-111 /root/abcd       {
"AcceptRanges": "bytes",
"LastModified": "Tue, 17 May 2022 11:44:03 GMT",
"ContentLength": 10485760,
"ETag": …
```

rgw_sal_motr: [CORTX-31312] PutObjectTagging: Update attributes for an object

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Observed several issues of null version-id in list-object-versions, HEAD and GET object API.
Issues and approaches are noted in the confluence document here - https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1007091811/Findings+on+RGW+versioning+issues+WIP
Solution:
To handle null version-id cases, followed following approach:
- Generate version-id for null versioned object and append that with _null string.
Example: obj1 will be stored as zWuUXuFIHgyDjydaFnK-ffezsDuFdpw_null.
- Create an additional index entry for all objects to hold the metadata of null version (Key : obj1[null])
- In case of suspended and un-versioned bucket, update the value of additional null entry (Key : obj1[null])
Signed-off-by: Priyanka Salunke [priyanka.s.salunke@seagate.com]
- …

rgw_sal_motr : [CORTX-30178] Fix for handling null version-id issues 

---

src/rgw/rgw_sal_motr.cc

In the recent commit d70996c7 a regression was introduced
which may cause corrupted data on GET in some regraded read
cases. For example, if some unit was not written due to the
server failure, we will get zeros for this unit on read
without any error (becasue of M0_OOF_HOLE flag), so the user
will even not know that he is getting corrupted object data.
Solution: don't use M0_OOF_HOLE.
Also, we are fixing the code duplication issue around the
usage of get_optimal_bs() function. This is a refactoring of
recent commits d70996c7 and c918d095.
Closes #222.
<details> …

rgw_sal_motr: [CORTX-31594] fix getting corrupted data

---

src/rgw/rgw_sal_motr.cc

Problem:
delete-object API is not working for unversioned bucket.
Solution:
Pass version-id in key name(obj1[version-id]) while deleting the object.
<details> …

rgw_sal_motr :[CORTX-31533] Fix delete-object API for unversioned object

---

src/rgw/rgw_sal_motr.cc

- Complete multipart upload API overwrites the object entry in bucket versioning case. 
Solution:
- In the MotrMultipartUpload::complete() function, added a check for versioning. 
- PUT the new key as objectname_versionid in complete() function.
- Used the MotrObject::update_version_entries() function to update the older object version entries.
<details>
- `jenkins …

rgw_sal_motr: [CORTX-30149] Added versioning support for complete multipart upload API

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem:
MotrObject::set_obj_attrs() and MotrObject::get_obj_attrs() has similar/common code
Resolution:
Refactor it by moving the common code into a separate function
<details> …

rgw_sal_motr: [CORTX-31435] ObjectTagging: Refactoring set and get obj_attrs

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_usage.cc

Problem : User level stats counting for Motr SAL layer
Solution : Fetched stats from newly added user stats table
Signed-off-by: Diwakar92 <diwakar.kumar@seagate.com>
<details>
</details>

CORTX-30363:User level stats counting for Motr SAL layer

---

src/rgw/rgw_sal_motr.cc

RGW SAL layer does not print every rc return from libmotr calls in case of error.
This sometimes makes it difficult to debug any issue.
Add more logs in order to print rc for every failure received from libmotr in rgw sal.
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).
- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.
<details>
- `jenkins retest this …

rgw_sal_motr: [CORTX-29873] - improve logging in rgw sal

---

src/rgw/rgw_sal_motr.cc

Multipart-upload is not working as expected for null version-id scenarios.
Solution:
To handle the null version-id cases in multipart upload API, created null reference key(obj/null) at the time of object PUT(same way as we used in case of normal obj)
Signed-off-by: Priyanka Salunke [priyanka.s.salunke@seagate.com]
<details> …

rgw_sal_motr : [CORTX-30149] Fix for handling null version-id issues in multipart upload

---

src/rgw/rgw_sal_motr.cc

Delete object API is not working as expected for multipart upload object for unversioned bucket after adding null version-id code changes
Solution:
For unversioned bucket, Pass the key name as `objectname[version_id]` to the delete object API for multipart object.
<details>
- …

rgw_sal_motr : [CORTX-30149] Fix multipart object issues in Delete Object API for unversioned bucket

---

src/rgw/rgw_sal_motr.cc

In case of version suspended bucket delete-object with null version is
not working.
Solution:
Delete null reference key after deleting null version delete-marker's entry.
<details>
- …

rgw_sal_motr :[CORTX-30184]: Fix delete-object with null version in version suspended bucket

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Delete object API is not working as expected for multipart upload object for versioning enabled/suspended bucket after adding null version-id code changes.
Solution:
To fix this issue, pass the specific version-id to the delete object function in case of multipart object.
<details>
- `jenkins test dashboard …

rgw_sal_motr : [CORTX-30149] Fix multipart object issues in Delete Object API for versioned bucket

---

src/rgw/rgw_sal_motr.cc

When delete-marker is the current entry present in bucket, then in get/head API response it shows
delete-markers attributes. The expected result is it should throw the NoSuchKey error.
Solution:
Return -2 if the current entry of the object is delete-marker.
<details>
- `jenkins …

rgw_sal_motr:[CORTX-30184] Fix get/head object issue in case of delete-marker entry is current entry present in the bucket.

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Merging 'versioning-feature' branch into 'main'
**Problem statement:**
Need versioning for Multipart APIs, Delete and Bulk Delete APIs, handle null version-id usecase and fix issues for GET and HEAD object API.
**Solution**:
Fixed following issues for unversioned/version enabled/version suspended bucket.
1. Simple object null version-id cases.
2. Multipart upload null version-id cases.
3. Fixed delete-object and delete-objects issues.
4. Get and head object issues.
Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>
<details> …

rgw_sal_motr: [CORTX-30178] Handling null version-id use case, Enabling versioning for Multipart APIs, Delete and Bulk Delete APIs

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem: Enabled tagging APIs put-object-tagging,get-object-tagging,delete-object tagging APIs on version enable bucket.
Solution: Handled all the version/ null version cases for the tagging APIs.
Signed-off-by: shraddha ghatol <shraddha.j.ghatol@seagate.com>
<details> …

rgw_sal_motr: [CORTX- 31606] : Enabling versioning support for Object Tagging APIs

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem:- When doing multipart object overwrite using simple object,
multipart object parts was not getting deleted,resulting in leak.
Solution:- Added a code in MotrAtomicWriter::complete function, so that
it will check whether the old object which is present in bucket
is multipart or simple object,according to that it will call the
respective functions to delete the object.

rgw_sal_motr: [CORTX-31438] Fix for overwrite of multipart object with simple object

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_usage.cc

Issue:
- next_query_by_name() crashes when zero entries are returned and so does
list_buckets() and read_stats().
- Fixing the issue by returning 0 when no entries are present in the index.
Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
<details> …

rgw_sal_motr: [CORTX-30363] Fix user-stats bug for user with no buckets

---

src/common/options/rgw.yaml.in
src/rgw/motr/addb/README.md
src/rgw/motr/addb/rgw_addb.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem: RGW SAL Motr code and incoming RGW requests shall be
instrumented with ADDB probes to reconstruct io-path in scope of
debugging and performance-related work.
Solution: Basic Motr SAL operations (open/write/read/close/delete_obj
and do_idx_op) are instumented with ADDB probes. Handled three types of
operations: S3 Put, S3 Get and S3 Delete multiple objects.
ADDB is Motr sub-system designed for collecting system information
for further analysis. ADDB stands for Analytic and Diagnostic Data-Base.
ADDB probes, added into RGW code, are saved into binary file during RGW
execution and can be converted into human-readable format for
post-execution analysis. Typical ADDB record contains timestamp,
sub-system id (Motr client, CAS, RPC, ...) and passed parameters.
Signed-off-by: Maxim …

rgw_sal_motr: [CORTX-29019] Instrument RGW with ADDB probes

---

src/rgw/rgw_sal_motr.cc

Signed-off-by: Rahul Tripathi <rahul.tripathi@seagate.com>
Problem: After Merging PR #246 put-object-tagging stopped working.
Solution: This PR Reverts Seagate/cortx-rgw#246
<details>
</details>

rgw_sal_motr: [CORTX-30354]: Revert "rgw_sal_motr: [CORTX-30354]: Get object tags count using get-object"

---

src/rgw/rgw_sal_motr.cc

Problem:
Empty size objects are not removed from the un-versioned bucket using delete object API.
Solution:
To handle this issue, added the object size conditions in the delete object function.
<details> …

rgw_sal_motr : [CORTX-31850] Fix for empty size object deletion in un-versioned bucket

---

src/rgw/rgw_sal_motr.cc

- User & Bucket Quota is compared and validated at Object Put operation to ensure that quota limits are not breached.
- `MotrBucket::check_quota()` function is implemented for the same.
```
JFYI:
* There are 2 types of bucket quotas. 
1. Bucket quota applied to a specific bucket 
2. User level bucket quota
* If a bucket quota is added for a particular bucket it will take precedence over User level bucket quota.
```
Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
<details> …

rgw_sal_motr: [CORTX-31201] Add User & Bucket Quota Validation

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Currently, if user requested range get for the object,
we always read all units from the start of the parity group,
even if their data is not within the specified range. This
generates needless fops, network traffic and the server I/O.
Solution: fix read_mobj() to fetch only the needed units
from the start of the parity group. Also, optimise the code
logic and improve its readability.
<details> …

rgw_sal_motr: optimise range get

---

src/rgw/rgw_sal_motr.cc

Such error can happen, for example, when there are too many
failures in the cluster which are not tolerable by motr, so
the pool version is not available and m0_layout_find_by_objsz()
cannot return any meaningful result.
Solution: handle errors from m0_layout_find_by_objsz().
<details>
- …

Handle error from m0_layout_find_by_objsz()

---

src/rgw/rgw_sal_motr.cc

- Observed crash in delete objects (bulk delete) API in multipart object, when delete marker is present for an object.
- Delete object API is not working for delete marker with --version-id as null parameter.
Solution:
- Added the delete marker condition in the function for multipart objects. If delete marker not present for an object, then fetch the instance and delete the object. 
<details>
- …

rgw_sal_motr : [CORTX-31843] Fix delete objects API issues in multipart upload

---

src/rgw/rgw_rest_user.cc

Problem:
The quota check for max_size rounds up the new object size to the nearest 4k and compares it to
the total rounded size of all the objects in the bucket. 
This is why, if the object size is less than 4k and the user/bucket quota is enabled, the quota limit
exceed error is raised and the put operation fails.
Solution:
RGWQuotaInfoRawApplier can be used to compare the raw size of an object with the raw size sum of all the 
objects.
To use this Applier we need to set the `check_on_raw` boolean in the user & bucket quota to `true`.
* check_on_raw is by default false and there is no way to set it true.
* Adding an argument in set-quota API to set the check_on_raw value.
* This will allow the user to validate max_size from quota with the size of objects
instead of rounded size. …

rgw_rest_user: [CORTX-32088] Accept `check_on_raw` arg for SetUserQuota

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem:
While adding the new null version in the suspended/unversioned bucket
deleting the previous null object from the bucket index only.
Solution:
Delete object from motr store as well as from the bucket index.
<details>
- …

rgw_sal_motr: [CORTX-31925] Fix object leak for null version object.

---

src/rgw/rgw_rest_bucket.cc

check_on_raw enables validating bucket quota with raw size of object
instead of the rounded size.
There was no way to set this value in sal_motr to accepting it as an arg
in set bucket quota api.
Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
<details> …

rgw_rest_bucket:[CORTX-31201] Enable `check_on_raw` for set individual-bucket-quota

---

src/rgw/rgw_multi.h
src/rgw/rgw_obj_manifest.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Features:
1. Support Stats calculation for multipart objects
2. Correction of Stats counting for object over-write case.
3. Calculation of actual size of a simple object.
4. Calculation of actual size of the multipart object.
<details> …

rgw, rgw_sal_motr: [CORTX-31877] Add features to User Stats Calculation

---

src/rgw/rgw_sal_motr.cc

- Currently, we store null version reference key for each object as object/null. But with bucket listing operation, its matching with prefix pattern 'PRE /', hence this null object is getting listed as a part of list objects. So, we can see two entries for single object.
Solution:
- Updated the way to store the null reference entry e.g. object^null
- Used '^' (caret) as delimiter
<details>
- …

rgw_sal_motr : [CORTX-31969] Update the delimiter for null reference entry

---

src/rgw/rgw_sal_motr.cc

Problem:
In un-versioned or suspended bucket, version-id field with null value is displayed in response of GET and HEAD object API.
In case of RADOS & AWS, this null version-id field is ignored from above API response.
Solution:
If bucket is un-versioned/suspended and version-id is null then delete the versiond-id value from result.
Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>
<details>
- `jenkins …

rgw_sal_motr : [CORTX-31876] for unversioned/suspended bucket, skip versionId parameter for GET/HEAD object API response

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

get-object API is failing for invalid null version-id parameter.
Solution:
Return -2 if key or version-id is not present in the bucket.
<details> …

rgw_sal_motr:[CORTX-32120] get-object is failing for invalid  null version-id.

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

No support for copy object in current implementation.
1. Use ReadOp class to read from source object.
2. Use Atomic writer class to write to destination object.
Signed-off-by: Deepak Mahale <deepak.mahale@seagate.com>
<details> …

rgw_sal_motr: [CORTX-31439] Add support for copy object in same zonegroup

---

src/rgw/rgw_sal_motr.cc

There is no log that have s3 obj name with motr object details in single log line.
Add log corelating s3 object key with motr obj details like oid, fid, lid.
<details> …

rgw_sal_motr: [CORTX-31638] add log for motr object details

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

After the recent fix in Motr (see Seagate/cortx-motr#1866)
we may get "too many failures" error when reading the last
parity group of the object in degraded mode.
Solution: when reading units from the last parity group,
read all the existing ones, and specify the new M0_OOF_LAST
flag to indicate where the object ends, so that libmotr
could know which units to use for the data recovery.
Relates to Seagate/cortx-motr#1817.
<details> …

rgw_sal_motr: [CORTX-31617] fix reading in degraded mode

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

If the maximum size of accumulation buffer (32M) is not multiple
of object's parity group size, the writing of blocks will happen
with RMW (read modify write), which is not only suboptimal, but
also is not supported by the degraded mode I/O in Motr.
Solution: don't write all the accumulated data on every write()
call, but only when it is the last write() call for the object.
And when it's not the last call, continue accumulation up to the
optimal bs, and write in full bs.
Also, use M0_OOF_LAST flag to avoid RMW on writing the last
non-fully-spanned parity groups.
Note: this PR must be landed after https://github.com/Seagate/cortx-motr/pull/1866.
Closes #289.
<details> …

rgw_sal_motr: [CORTX-32141] fix possible RMW on writes

---

src/rgw/rgw_sal_motr.cc

This is a regression introduced at commit 4fd026b0139: the
size of motr object part (obj_size) is not set and, as result,
bs becomes zero at read_mobj() here:
// At the last parity group we must read up to the last
// object's unit and provide the M0_OOF_LAST flag, so
// that in case of degraded read mode, libmotr could
// know which units to use for the data recovery.
if ((size_t)off + bs >= obj_size) {
bs = roundup(obj_size - off, get_unit_sz());
flags |= M0_OOF_LAST;
Which eventually leads to crash at bl.append_hole(bs).
Solution: initialise part obj_size at get_part_objs().
<details>
- …

rgw_sal_motr: [CORTX-32291] fix crash on reading mpart obj

---

src/rgw/rgw_sal_motr.cc

The regression was introduced at commit 0ed9f66eaeb, after
which the object size recorded in its metadata on put-object
operation is always aligned to the unit size. So if the real
object size is not aligned to its unit size, the recorded
size will be wrong. (So the amount of data on get-object
operation also will be wrong.)
Solution: fix the code at MotrAtomicWriter::write() to
record the real object size in its metadata record.
<details>
- …

rgw_sal_motr: [CORTX-32310] fix obj size on put

---

src/rgw/rgw_sal_motr.cc

Values in `CommonPrefixes` were restricted to one character after delimiter, updated length from one to delimiter's length to match values of `CommonPrefixes` as per AWS specifications
```
$ aws s3api list-objects --bucket test-bucket-932492 --delimiter "education" --endpoint-url http://127.0.0.1:8000 --profile mgwuser 
{
"Contents": [
{
"Key": "german/personal/11mfile",
"LastModified": "2022-06-16T09:18:04.662Z",
"ETag": "\"c8d4d0fa8e22369f05c6013405dddd1f\"",
"Size": 5242880,
"StorageClass": "STANDARD",
"Owner": {
"DisplayName": "mgwuser",
"ID": "mgwuser"
}
},
{
"Key": "lipsa/personal/11mfile",
"LastModified": "2022-06-16T09:18:24.851Z",
"ETag": "\"c8d4d0fa8e22369f05c6013405dddd1f\"",
"Size": 5242880,
"StorageClass": "STANDARD",
"Owner": …
```

rgw_sal_motr: [CORTX-32135] Fix for mismatch in response for `List Objects` with delimiter

---

src/test/rgw/test_rgw_iam_policy.cc

Problem:
In PR #316 we commented IPPolicyTest unittest as IPPolicyTest
unittests were crashing.
Solution:
Uncommented IPPolicyTest unittests. A new story will be
creating for fixing this crash.
<details> …

rgw: [CORTX-29924] Uncommented IPPolicyTest unittests

---

src/rgw/rgw_iam_policy.cc

**Problem** : Same SID's allowed in put-user-policy operation
**Root Cause**: There is no check for detecting same SIDs in a policy document
**Solution** : Introduced a new set sid_set and adding each sid to it.
If sid is already present, we are throwing error "MalformedPolicyDocument"
Signed-off-by: Sanal Kaarthikeyan 
<details>
- …

rgw: [CORTX-32034] Fixed same Sid issue in put-user-policy operation

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

When writing an object we are getting object's metadata
several times: sometimes two, sometimes even three times,
when there is no real need. This generates a lot of
redundant fops in the network and redundant load on the
servers.
The need of sending several GET requests comes from the
concept of using null-reference entry, which references
the real null entry in the metadata records: we get the
null reference entry first, read the reference key from
it (the key-instance hash), and then we get the real null
entry by using the key name and its instance hash.
Solution: refactor & simplify the code: 1) don't store
the key instance hash for the null entries, there is no
real need for this; this allows to 2) get rid of the null
reference entry concept entirely.
Testing: tested put, get, delete …

rgw_sal_motr: [CORTX-32326] fix redundant mdata i/o

---

src/rgw/rgw_rest_s3.cc

Wrong paramter names are used to read request headers for conditional parameters
related copy-object api because of that passing conditional parameters in the request
has not effect.
Fix parameter names in get_param() for copy-object.
Note: This fix is also available in ceph/master branch. This might cause conflict while merging it to ceph/master branch. Conflict should be resolved if seen.
<details>
- `jenkins test make check …

rgw: [CORTX-31445] - fix conditional parameter for copy-object api

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem:
- delete_obj() function became bulk due to the addition of delete marker code.
- VersionId response header is returned in DELETE Object response in an unversioned bucket
Solution:
- Create a separate function for delete-marker creation.
- Assign a value to the 'result.version_id' only in case of version enabled and suspended case.
<details>
- `jenkins …

rgw_sal_motr:[CORTX-31978] Refactoring delete marker code.

---

src/rgw/rgw_sal_motr.cc

Currently, null-version record always appears in the result of
the list-object-versions command for the specified object, even
when --max-keys limit is specified and there are more recent
objects in the bucket than the null-version. For example, in
case when --max-keys=1, null-version always will be returned in
the result regardless of its modification time (mtime) to the
other versions of this object.
AWS S3 specifies that the order of the object version returned
in the list-object-versions should be the same in which the
objects were put, i.e. the latest ones should be at the top.
This should work also when --max-keys limit is set by the user.
Solution: fix the code at MotrBucket::list() to return the
object versions in the correct way when the null-version is
present and --max-keys …

rgw_sal_motr: [CORTX-32383] fix null-version in list-object-versions

---

src/rgw/rgw_sal_motr.cc

Problem:
In a versioning Enabled/Suspended bucket, where DeleteMarker exists, GET Object Tagging API without versionId and with DeleteMarker's versionid is returning an empty tagset. Instead, it should return a 'NoSuchKey' error.
Solution
Handled and restricted adding tags to delete marker metadata at get_object method, when some one try to get/ add tags to delete marker it will raise validation error.
Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>
<details>
- `jenkins test make …

rgw_sal_motr:[CORTX-32128] Restricted adding tags to delete marker metadata

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

- For multipart object, observed a crash when user tries to delete the previous (non-latest)  object version with version-id parameter.
- Root cause is, in the `MotrMultipartUpload `class we are not storing the version-id for an object. When user tries to delete a specific multipart object version (non-latest) by specifying the version-id parameter, it always tries to fetch latest object entry instead of specified object version (`list_parts() -> get_bucket_dir_ent()`)
Solution:
- In the `MotrMultipartUpload `class added a new variable `version_id` to store the specific version-id for multipart object, along with getter and setter methods.
- Now, this version_id variable will store the version-id passed by user, hence in the `get_bucket_dir_ent()` function, it fetches …

rgw_sal_motr : [CORTX-32424] Fix for delete previous object using version-id

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

…
Ticket: https://jts.seagate.com/browse/CORTX-31446
Problem Description:
Timeout error for large-sized(more than 3GB) copy-object operation.
Problem Solution:
Call the RGWCopyObj::progress_cb after writing every part, which sends the partial response to the client so that it does not time out.
Signed-off-by: Pranav Diliprao Pawar <pranav.pawar@seagate.com>
<details>
- `jenkins test dashboard …

rgw_sal_motr : [CORTX-31446] Copy-object: send keep alive to client to avoid req timeout

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Currently, the format of null-version objects keys stored in
bucket index in Motr does not have any suffix. But versioned
objects do have the suffix: "key[instance]". This leads to the
situations when null-objects can be fetched separately from
their versioned objects, in case there are some other objects
with the same key prefix. For example, consider the following
case:
obj1
obj1-2
obj1[instance]
It's because "-" symbol goes before "[" in the ASCII-table.
As a result, the output of list-object-versions command for such
cases will be broken.
This also may affect the correct setting of IsLatest flag for
the object versions in the versioned bucket, when the new
version is put into the bucket or some existing one is deleted
from the bucket. It's because when we find the latest object …

rgw_sal_motr: [CORTX-32423] fix listing of same-prefix objs

---

src/rgw/rgw_sal_motr.cc

problem:
1. Create two users (user1 with user-policy caps and user2 without caps)
2. Create bucket "bucket" under user1
3. Create object in bucket
4. Apply below policy on user2 using user1 profile
`{
"Version": "2012-10-17",
"Statement": {
"Effect": "Allow",
"Action": ["s3:ListBucketMultipartUploads", "s3:AbortMultipartUpload"],
"Resource": "arn:aws:s3:::*"}
}`
5. create multiparts uploads (without completing the mutipart) using user1
6. abort multipart upload using user2
An error occurred (NoSuchKey) when calling the AbortMultipartUpload
operation: Unknown
solution:
`bucket.owner` - Gives us current requesting user
`bucket.info.owner` - Gives us actual bucket owner
Passing actual bucket owner to `update_bucket_stats` fix the issue.
Signed-off-by: Parayya Vastrad …

rgw_sal_motr: [CORTX-32402] Fix for AbortMultipartUpload failing with NoSuchKey

---

src/rgw/rgw_sal_motr.cc

Problem:
rgw_obj_key::get_index_key() api has some specially handling for ns (namespace) which is spefic to rados backend.
If obejct key starts from `_` then get_index_key appends one more `_` to the key name.
This causes issue during lookup for the same key.
Solution:
Don't use rgw_obj_key::get_index_key() api in motr sal.
Also removed un-used code.
Signed-off-by: Saurabh Jain <saurabh.jain2@seagate.com>
<details>
- …

rgw_motr_sal: [CORTX-32463] fix GET api for object starting from '_'

---

src/rgw/rgw_sal_motr.cc

Update Stats behaviour for multipart upload sessions
Increment object count in a bucket per part upload in a multipart session.
At the multipart complete stage adjust the object count so that only one
object is added in the end.
If the user quota is of 3 objects then the user can not upload more than 3 parts 
for a single multipart object. (This is because we are updating the object count
for each part.)
Increment the object count only at a multipart init stage. 
Increment the object size on the upload of each part. (no update for obj_count).
<details>
- …

rgw_sal_motr: [CORTX-32487]  update stats behavior on multipart upload

---

src/rgw/rgw_sal_motr.cc

JIRA ticket : https://jts.seagate.com/browse/CORTX-32966
Problem Description:
Pointer variable was not freed at one the place in SAL layer (int MotrBucket::check_quota) which was leaking the memory.
Problem Solution:
Freeing the pointer after its use.
Signed-off-by: Pranav Diliprao Pawar <pranav.pawar@seagate.com>
WORKLOAD:
numSamples : 1
numClients : 1
objectSize : 80MB
<details><summary> Leak Summary Before: </summary>
LEAK SUMMARY:
definitely lost: 61,650 bytes in 52 blocks
indirectly lost: 5,535 bytes in 1,069 blocks
possibly lost: 0 bytes in 0 blocks
still reachable: 6,766 bytes in 22 blocks
suppressed: 0 bytes in 0 blocks
</details>
<details><summary> Leak Summary After: </summary>
LEAK SUMMARY:
definitely lost: 1,650 bytes in 16 blocks
indirectly lost: 288 bytes in 3 blocks …

rgw_sal_motr : [CORTX-32966] Fix memory leaks in RGW

---

src/rgw/rgw_sal_motr.cc

rgw_obj_key::get_index_key() api has some specially handling for ns (namespace) which is spefic to rados backend.
If obejct key starts from '_' then get_index_key appends one more '_' to the key name.
This causes issue during lookup for the same key.
Convert cls_rgw_obj_key type to rgw_obj_key before comparing object keys or creating index keys.
"rgw_motr_sal: [CORTX-32463] fix GET api for object starting from '_'"
This reverts commit a1584461394babb5183c9f21806be64ccacb27b2.
Reason: We have to use rgw_obj_key::get_index_key() function to support rgw framework.
Signed-off-by: Saurabh Jain <saurabh.jain2@seagate.com>
<details>
<summary>Show available Jenkins …

rgw_sal_motr: [CORTX-32463] handle _ (underscore) in object key name

---

src/rgw/motr/addb/README.md

Problem:
Codacy throws warning in src/rgw/motr/addb/README.md on inlined code block.
Solution:
Label code block with `console` attribute.
Signed-off-by: Maxim Malezhin <maxim.malezhin@seagate.com>
- [Y] Doc update (no ticket needed)
- [Y] Code cleanup (no ticket needed)
- [Y] No impact that needs to be tracked
- [Y] Updates relevant documentation
- [Y] No tests
<details> …

rgw_sal_motr: Fix Codacy warning in ADDB readme file

---

src/rgw/rgw_sal_motr.cc

problem:
Tagging is not enabled for copy-object API with motr as backend.
solution:
Enabled tagging support for copy-object with --tagging-directive as COPY and REPLACE
<details> …

rgw_sal_motr: [CORTX-31442] Enable tagging for copy-object

---

src/rgw/rgw_rest_user.cc

Problem : User list with max-entries as special characters is not working as expected
Solution : Checked if max-entries provided through REST API doesn't contain numeric values, returning as invalid argument.

rgw: [CORTX-31349] Fix for user list api with special characters in max-entries attribute

---

src/rgw/rgw_sal_motr.cc

In List Object Versions API : 
- For invalid version-id-marker value, it is showing all object versions.
Solution:
- Return `InvalidArgument` error in case of invalid version-id-marker. 
- Handle valid null version object entry in list response if user passes key-marker and version-id-marker parameter in ListObjectVersions request.
<details> …

rgw_sal_motr : [CORTX-32361] Fix invalid version-id-marker issue in a List Object Versions API

---

src/rgw/rgw_op.cc

Problem statement:
Copying of object across same/different bucket fails using 'aws s3 cp' command
Solution:
Added NotImplemented error for uploadPartCopy operation
<details> …

rgw_sal_motr: [CORTX-33664] Add `NotImplemented` error for uploadPartCopy operation

---

src/rgw/motr/gc/gc.cc
src/rgw/motr/gc/gc.h

GC thread processing logic
The GC thread will acquire GC index and process the object entries for
deletion either up-to the count governed by "rgw_gc_max_trim_chunk" or
time allowed by "rgw_gc_processor_max_time".
<details> …

rgw_sal_motr, motr_gc: [CORTX-33180] GC thread processing logic

---

src/rgw/rgw_rest_s3.cc

Problem:
Observed discrepancy with AWS for DeleteBucketTagging API.
In ceph-RADOS DeleteBucketTagging API returning status code=200
on success, while in AWS it is returning status code=204.
Solution:
Assign op_ret=STATUS_NO_CONTENT when DeleteBucketTagging operation
is successful.
<details>
- …

rgw: [CORTX-31471] Return correct status code in case of DeleteBucketTagging API.

---

src/rgw/rgw_sal_motr.cc

Problem statement: Handle errors for copy object operation
Solution: Added detailed error message and changed some error codes to make it AWS compliance. 
<details> …

rgw_sal_motr: [CORTX-33105] - Handle errors for copy object operation

---

src/rgw/rgw_sal_motr.cc

List-objects API returning number of objects with
version-id-marker attribute is mismatching in s3tests test suite.
```
bucket_name = _create_objects(keys=['foo', 'bar', 'baz'])
client = get_client()
response = client.list_objects(Bucket=bucket_name, Marker='baz', MaxKeys=2)
Keys - ['baz', 'foo'] 
```
Here, we should get only foo
Below ceph s3tests are failing with assertion
errors on setup with motr as backend. number of objects
returning are mismatching with s3test.
```
's3tests_boto3.functional.test_s3:test_bucket_list_many',
's3tests_boto3.functional.test_s3:test_bucket_list_maxkeys_one',
's3tests_boto3.functional.test_s3:test_bucket_listv2_many',
's3tests_boto3.functional.test_s3:test_bucket_listv2_maxkeys_one'
```
Solution:
In the list_objects(MotrBucket::list) …

rgw_sal_motr : [CORTX-33538] Fix cephs3test issues of list-objects API

---

src/rgw/rgw_sal_motr.cc

GET and HEAD object with null version-id does not contain "VersionId" field in the response
Solution:
In GET/HEAD object with --version-id null parameter for simple and multipart object, set the `ent.key.instance` value as `null` to show the VersionId field in the response.
<details>
- `jenkins test dashboard …

rgw_sal_motr : [CORTX-32387] Fix null version-id issues in GET/HEAD object API

---

src/rgw/rgw_sal_motr.cc

**Problem** : Object tagging tests were failing intermittently due to tags were not set through setObjectTagging API.
**Solution** : For multipart object case, in setObjectTagging API, code was returning success code without setting tag values to given object hence removing this code.For Multipart objects, tagging support is already handled in different flow.
<details> …

rgw_sal_motr : [CORTX-33574] Fixed  Object tagging tests failing intermittently issue

---

src/rgw/rgw_sal_motr.cc

**Problem Statement**:
- Get object tagging API without version-id parameter does not return tagset for latest object versions
- Put object tagging for null version-id, adds new null object entry instead of overwrite the existing one.
**Solution**:
- In put-object-tagging, removed the modified time (mtime) statement
- For Get/HEAD object API in case of null object entry, remove the "null" from instance to avoid "VersionId" field in the response.
<details>
- `jenkins …

rgw_sal_motr : [CORTX-32485] Fix issues for get-object-tagging API without version-id parameter in versioning suspended bucket

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem:
If copy operation failed after copying some data, its throwing an invalid XML error due to partial progress response. i.e rgw was not closing 'CopyObjectResult' tag in case of failure.
progress_cb() is not sending copy progress percentage or the total size of the object being copied during the copy operation,  but periodically keeps sending copied bytes till now, which is not enough to know copy progress anyways as total obj size not known, and in negative cases, no proper response is sent by Copy object, instead progress_cb() response is seen, which is originally meant as partial response only.
Solution:
Replace progress_cb() call from rgw_sal_motr layer, with dump_continue() signal, which responds with HTTP 100 Continue header to avoid client timeout during the long copy …

rgw_sal_motr:[CORTX-33799] Handle progress_cb response in case of copy-object operation failure.

---

src/rgw/motr/gc/gc.cc
src/rgw/motr/gc/gc.h
src/rgw/motr/sync/motr_sync.h
src/rgw/motr/sync/motr_sync_impl.cc
src/rgw/motr/sync/motr_sync_impl.h
src/rgw/rgw_sal_motr.cc

rgw_sal_motr, motr_gc: [CORTX-32689] Integrate locking mechanism with Motr GC

---

src/rgw/rgw_sal_motr.cc

Problem:
CopyObject operation fails for zero byte object with 'NoSuchKey' error.
Solution:
Read/write to Motr only if object size is greater than zero.
<details> …

rgw_sal_motr: [CORTX-33766] Fix for CopyObject API for zero byte object.

---

src/rgw/rgw_sal_motr.cc

Problem:
After DI changes, the unit size is limited to 1MB for objects >= 1MB.
In SNS 3+2 config, the first part object for a 10MB object is partially
uploaded, causing EIO (-5) error during Get obj API call.
Solution:
Use part object size to calculate optimal block size.
<details>
- `jenkins …

motr_sal: [CORTX-32689] Fix multipart download issue

---

src/rgw/rgw_sal_motr.cc

Problem : 
"NoSuchKey" error was returning when tried copyObject API after applying valid IAM policy on IAM user.
Solution : 
Previously in copy object API it was considering owner of destination bucket as "user id" and not the actual owner of the bucket. Fixed that by changing owner as destination bucket owner.
Sample policy example with command is given in - https://jts.seagate.com/browse/CORTX-33109?focusedCommentId=2421624&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2421624
<details>
- …

rgw_sal_motr :[CORTX-33109] Fixed noSuchKey error in CopyObject API for IAM Policy

---

src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Problem: No limit on the size of data in a write IO made during multipart
part object write operation. Due to this, it may lead to crossing the lib motr's
internal max data transfer size in one write IO.
Solution.
Set the max threshold to 32MB. This makes multipart object write IO
at par with simple object write IO.
Signed-off-by: root <root@ssc-vm-g4-rhev4-0451.colo.seagate.com>
<details>
- …

rgw_sal_motr: [CORTX-34075] Enhance multipart object write IO

---

src/rgw/motr/gc/gc.cc
src/rgw/motr/gc/gc.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Commit 1:
Fixing the part index table name to make it work for both
versioned and unversioned multipart objects.
Commit 2:
Added a utility function in the Meta class to get the string version of OID.
Signed-off-by: Sumedh Anantrao Kulkarni <sumedh.a.kulkarni@seagate.com>
<details>
- `jenkins …

rgw_sal_motr: [CORTX-34122] support versioned multipart delete using GC

---

src/rgw/motr/gc/gc.cc
src/rgw/motr/gc/gc.h
src/rgw/rgw_admin.cc
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Add `count` as number of entries in all GC queues and `inaccessible_queues` as list of GC queues which are inaccessible.
Sample Output: 
```
$ bin/radosgw-admin gc list --no-mon-config
2022-09-06T02:10:47.457-0600 7fdb3dc8f680 -1 WARNING: all dangerous and experimental features are enabled.
2022-09-06T02:10:47.458-0600 7fdb3dc8f680 -1 WARNING: all dangerous and experimental features are enabled.
2022-09-06T02:10:47.459-0600 7fdb3dc8f680 -1 WARNING: all dangerous and experimental features are enabled.
2022-09-06T02:10:47.459-0600 7fdb3dc8f680  1 RGW CONF BACKEND STORE = motr
2022-09-06T02:10:47.459-0600 7fdb3dc8f680  1 RGW BACKEND STORE = motr
{
"entries": [
{
"tag": "0x11a119a:0xefa4000000300009",
"name": "testbkt1/test_50m_obj-0\u0007.part.00000004",
"deletion_time": …
```

rgw: [CORTX-34081] Add `count` and `inaccessible_queues` in GC list output

---

src/rgw/rgw_sal_motr.cc

GET/HEAD Object API with version id of a delete marker gives `404 (NoSuchKey)` error in the response.
Solution: 
Modified the error code and error message of GET/HEAD object API response to `405 (MethodNotAllowed)` in case of delete-marker.
<details>
- …

rgw_sal_motr : [CORTX-34167] Modify error code and error message of GET/HEAD object API

---

src/rgw/rgw_sal_motr.cc

Problem: Getting "UnknownError" while performing copy object using tagging directive COPY on source object with no tags
Solution : Error occurs only when we put fresh object (without tagging) in bucket and perform copy-object operation with --tagging -directive COPY. No need to return error if empty tags are present. Even if tags are empty copy operation should get successful with --tagging-directive COPY.
If tags are empty we were returning with -66 error from copy_object_same_zone() function.
<details>
- `jenkins test classic …

rgw_sal_motr: [CORTX-34113]Copy-Object API :Handled UnknownError while performing copy object using tagging directive COPY 

---

src/rgw/rgw_sal_motr.cc

Problem Statement: 
DELETE Objects API should return Deleted key, DeleteMarker and DeleteMarkerVersionId in response when a delete marker is created for an object in a versioned bucket
Solution:
Set the `delete_marker` variable to `true` to get "Deleted key, DeleteMarker and DeleteMarkerVersionId" in the response. 
<details>
- …

rgw_sal_motr : [CORTX-34168] Modified response fields of DeleteObjects API

---

src/rgw/motr/sync/motr_sync.h
src/rgw/motr/sync/motr_sync_impl.cc
src/rgw/motr/sync/motr_sync_impl.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

- Add `dpp` in `MotrLock` class as a private member and initialize it.
- Refactor the method and the call to the method `remove_lock(...)`.
- Add virtual destructors in MotrSync & MotrLockProvider classes.
- Move the log level declarations from the `rgw_sal_motr.cc` to the `rgw_sal_motr.h` file.
Signed-off-by: Sumedh Anantrao Kulkarni <sumedh.a.kulkarni@seagate.com>
<details> …

motr_sync, rgw_sal_motr: [CORTX-34177] refactor Motr Locking code

---

src/rgw/rgw_sal_motr.cc

Problem: 
During the Remove User code flow till the DeleteOp is instantiated for each obj from a bucket, we don't have the access to req_state ptr via RGWObjectCtx. This causes the addb.set_id(rctx) to fail, as it tries to access the req_id from null req_state ptr. 
Solution:
To avoid the above situation, guarded the addb.set_id() call by checking if we have the req_state ptr accessible.
If inaccessible then generate the new req_id for each delete req.
Signed-off-by: Sumedh Anantrao Kulkarni <sumedh.a.kulkarni@seagate.com>
<details> …

rgw_sal_motr: [CORTX-32697] support user remove with purge data

---

src/rgw/motr/gc/gc.cc
src/rgw/motr/gc/gc.h
src/rgw/rgw_sal_motr.cc
src/rgw/rgw_sal_motr.h

Currently, we create an additional index for each multipart-uploaded object to store its parts. If some server is down, the index creation operation would fail, thus failing the multipart upload.
Solution: don't create indexes on multipart uploads. Create an additional index to store objs parts when the bucket is created.
Closes #422.
<details> …

rgw_sal_motr: [CORTX-34181] allow multiparts with offline server
