.whitesource
Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
=> EOS-27560 add whitesource configuration to RGW repo

install-deps.sh
Don't try to install cortx-motr if it is already installed.
=> install-deps.sh: fix cortx-motr installation condition

.github/workflows/dco-check.yml
DevOps: DCO check workflow for RGW
<details>
</details>
=> DCO check workflow for RGW

src/rgw/rgw_sal_motr.cc
_[EOS-27520](https://jts.seagate.com/browse/EOS-27520):_
_Delete bucket API does not work._
_[EOS-28444](https://jts.seagate.com/browse/EOS-28444):_
_Delete empty bucket._
_[EOS-28445](https://jts.seagate.com/browse/EOS-28445):_
_Delete Bucket with Objects._
_[EOS-28446](https://jts.seagate.com/browse/EOS-28446):_
_Bucket stat and information update._
_[EOS-28447](https://jts.seagate.com/browse/EOS-28447):_
_Passing Ceph and Splunk tests for delete bucket._
1. Abort multipart function is plugged in remove bucket, but internals to be implemented in a seperate ticket. _[EOS-27630](https://jts.seagate.com/browse/EOS-27630)_
2. Sync user stat function is plugged in remove bucket, but internals need to be implemented in a seperate ticket.
3. Forward to master function is plugged in remove …
=> rgw_sal_motr: [EOS-27520] Changes for empty bucket deletion.

src/rgw/rgw_sal_motr.cc
=> CORTX-28054: Delete IAM user

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
=> CORTX-28869:Unable to create IAM user with email

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
=> CORTX-28057: Improve IAM user deletion logic

src/rgw/rgw_sal_motr.cc
Problem: 
Multipart Abort API fails during part deletion due to invalid state of of part's metadata (Motr oid, pv id and layout id) available in memory. The invalid state is caused due to no assignment of fetched metadata to the correct in-memory data structure.
Resolution:
After fetching part's metadata from Store, code changes are done to assign part metadata to the correct in-memory data structure, so that Motr's Open and then Delete operations on part are successful. This results in successful Abort API.
_[https://jts.seagate.com/browse/CORTX-27630]:_
_Multipart Abort API (backend part) support in RGW_
NA
NA.
During Multipart Abort, code is added to check if multipart upload id exists in storage. If no, **no_such_upload** error is returned. Also, modified code to assign loaded object …
=> rgw_sal_motr: [CORTX-27630] fix multipart abort

src/rgw/rgw_sal.cc, src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
**Problem:** 
`rgw_cache_enabled` config parameter from ceph.conf is not applied in MotrStore.
**Solution:** 
pass the use_cache boolean in `init_metadata_cache()` function and enable/disable the caching accordingly.
<details> …
=> rgw_sal_motr: [CORTX-29421] Add disable cache feature for MotrStore

src/rgw/rgw_sal_motr.cc
Support of same name bucket creation in different tenants with same userid
**Problem** - Tried to create a bucket with same name with same userid but different tenant
&emsp;tenant1
&emsp;&emsp;- user1 - create a bucket(testbucket) - success
&emsp;tenant2
&emsp;&emsp;- user1 - create a bucket(testbucket) - **ERROR: Bucket 'testbucket' already exists**
**Solution** - As bucket name are unique under a tenant. 
&emsp;Index name will be `<tenant>+"$"+<bucket_name>`
&emsp;Example - "motr.rgw.bucket.index." + `<tenant>$+info.bucket.name`;
<details>
- `jenkins retest …
=> rgw_sal_motr: [CORTX-29255] Fix BucketAlreadyExists error across different tenants

src/rgw/rgw_rest_user.cc
**Problem** : Delete IAM user returns 'InvalidArgument' instead of 'NoSuchUser' for a non existing user
**Root Cause**: tenant name is not being populated while delete operation.
**Solution** : added fix for populating tenant name during the execution
of user delete command.
**Jira Associated**: https://jts.seagate.com/browse/CORTX-29369
Signed-off-by: sanalpk [sanal.kaarthikeyan@seagate.com](mailto:sanal.kaarthikeyan@seagate.com)
<details>
- …
=> rgw: [CORTX-29369] Delete IAM user returns invalid response for non existing user

src/rgw/rgw_sal_motr.cc
An admin user should be able to list all the current users.
Implement `list_users()` function for motr.
`list_users()` function will use the existing `next_query_by_name()` function to get the list of all users from user index table. 
<details>
- …
=> rgw_sal_motr: [CORTX-28064] Enable user list api for Motr

src/rgw/rgw_sal_motr.cc
Current Status:
* PutUserPolicy & DeleteUserPolicy are working fine.
* GetUserPolicy & ListUserPolicies are failing
RCA:
* read_atrrs() method is not implemented, that's why fetching of Attrs
from kv store which stores the policy list is skipped, resulting in the
Get/List API failure.
Solution:
* Fetch the Attrs from kv store in the MotrUser::read_attrs() method.
* Authorization results and sequence diagrams are available [here](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/976322795/Sequence+Diagrams+User+Policy+CRUD).
<details> …
=> rgw_sal_motr: [CORTX-30294] Enable User Policy CRUD operations

src/rgw/rgw_sal_motr.cc
RGW SAL layer does not print every rc return from libmotr calls in case of error.
This sometimes makes it difficult to debug any issue.
Add more logs in order to print rc for every failure received from libmotr in rgw sal.
<details>
- …
=> rgw_sal_motr: [CORTX-29873] - improve logging in rgw sal

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
Changes:
1. Add/Delete User Stats index table on User creation/deletion. [commit 1](https://github.com/Seagate/cortx-rgw/pull/215/commits/4b46b9159e57ec5c6cc0c6c04ca3396dacb0ff6a)
2. Add/Remove bucket stats entry in the index table on bucket creation/deletion. [commit 1](https://github.com/Seagate/cortx-rgw/pull/215/commits/4b46b9159e57ec5c6cc0c6c04ca3396dacb0ff6a)
3. Implement read bucket stats. [commit 2](https://github.com/Seagate/cortx-rgw/pull/215/commits/ce8ecc952604dba4bb18251ab57795bc4d284dcb)
4. Update the total size and object count on object put and delete operations. [commit 3](https://github.com/Seagate/cortx-rgw/pull/215/commits/29ea0b1f915dedd1d35b5b382564d483cf82f8f3)
- Tests (select …
=> rgw_sal_motr: [CORTX-30362] Add & Update User Stats Index Table

src/rgw/rgw_sal_motr.cc
Observed issue in GET object API in multipart object upload
Solution:
Pass the version-id in the object name to list parts function in case of multipart upload
<details>
- …
=> rgw_sal_motr : [CORTX-30149] Fix GET object issues in multipart upload

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h, src/rgw/rgw_usage.cc
Support 
1. User Stats Fetching via /admin/user?stats&uid=<user_name>
2. Bucket Stats Fetching via /admin/bucket?stats&bucket=<bucket_name>
Added Functionalities: 
1. User stats index should be created per new user.
3. Add a blank entry per bucket in the owner user stats index on bucket creation.
4. Delete stats entry on bucket deletion.
5. Delete user stats index table on user deletion.
6. Implement read user stats & read bucket stats
7. Update the bucket stats on object create and delete operations.
Object overwrite & Versioned object put is handled.
<details> …
=> rgw_sal_motr, rgw_usage : [CORTX-30363] Support User Stats

src/rgw/rgw_sal_motr.cc
During multipart part overwrite, old part, if any existing, is deleted.
<details>
</details>
=> Handle multipart part overwrite

src/rgw/rgw_sal_motr.cc
=> Revert "rgw_sal_motr.cc: [CORTX-31836] Implement "size_actual" calculation per object"

src/rgw/rgw_op.cc
**Problem** : S3 Condition Key s3:VersionId is not being working as expected
**Root Cause**: VersionId is not being fetched and stored properly
**Solution** : Fetching VersionId from Store->info.env and stored in Store->env
so, Store->env can be used during condition evaluation.
Signed-off-by: Sanal Kaarthikeyan [sanal.kaarthikeyan@seagate.com](mailto:sanal.kaarthikeyan@seagate.com)
<details>
- …
=> rgw: [CORTX-31953] Fixed Broken S3 Condition Key s3:VersionId

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
=> rgw_sal_motr: [CORTX-31877] Support Stat counting for Multipart & Obj OverWrite case

src/rgw/rgw_multi.h, src/rgw/rgw_obj_manifest.h, src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
=> rgw, rgw_sal_motr: [CORTX-31836] calculate actual size for all types of objects

src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
Problem:
Delete Bucket action is not working, when IAM policy is applied on cross user.
Getting NoSuchKey when calling the DeleteBucket operation
Solution:
Unlinking bucket with correct user.
<details> …
=> rgw_sal_motr: [CORTX-32035] Fix for IAM Policy: Delete Bucket action is not working

src/rgw/rgw_sal_motr.cc
Problem:
In suspended bucket delete-marker's with new version-id is generated
instead of null version-id.
Solution:
If bucket is suspended then assign "null" value to delete-marker's
version-id.
<details> …
=> rgw_sal_motr:[CORTX-31962] Fix delete-marker's issue in case of suspended bucket.

src/rgw/rgw_sal_motr.cc
Problem:
Delete bucket is giving `NoSuchKey` for user with tenant
Solution:
Added validatio for user with tenant
<details>
</details>
=> rgw_sal_motr: [CORTX-32235] Fix for Delete Bucket failing for user with two set of keys

src/rgw/rgw_op.cc
problem:
IAM policy unittest was crashing when we run iam
policy unittests at IPPolicyTest test suite.
solution:
In #258 PR we added fix for versionId policy. In
this fix we added if condition for versionId
<details> …
=> rgw: [CORTX-32389] Fix for IAM IPPolicyTest crash

src/rgw/rgw_sal_motr.cc
Reverts Seagate/cortx-rgw#320
Signed-off-by: Sachitanand Shelake [sachitanand.shelake@seagate.com](mailto:sachitanand.shelake@seagate.com)
=> Revert "rgw_sal_motr: [CORTX-32383] fix null-version in list-object-versions"

src/rgw/motr/gc/gc.cc, src/rgw/motr/gc/gc.h, src/rgw/rgw_sal_motr.cc, src/rgw/rgw_sal_motr.h
* Push `{0_ObjTag: motr_gc_obj_info}` and `{1_ExpiryTime: motr_gc_obj_info}`
entry to the gc queues, i.e. motr dix.
* Call gc->enqueue() method on simple object delete request without
actually deleting the obj.
Signed-off-by: Sumedh Anantrao Kulkarni <sumedh.a.kulkarni@seagate.com>
<details>
- …
=> rgw_sal_motr, motr_gc: [CORTX-32689] Implement MotrGC::enqueue()

src/rgw/motr/gc/gc.cc, src/rgw/rgw_admin.cc
Added is_multipart flag in GC list output and updated deletion time to human readable time format.
<details>
</details>
=> rgw: [CORTX-32693] Improve output of GC list

src/rgw/motr/gc/gc.cc, src/rgw/motr/gc/gc.h, src/rgw/rgw_admin.cc, src/rgw/rgw_sal_motr.cc
Motr GC producer and consumer module implementation for multipart objects.
<details>
</details>
=> rgw: [CORTX-32694] Motr GC Implementation for Multipart Objects

src/rgw/rgw_sal_motr.cc
Problem statement:
- Improve logs level in RGW SAL layer
Solution:
- Introduced the macros for log level mapping
- Remove redundant logs
- Updated the code formats as per guidelines
- Added `__func__ ` in log statement
<details>
- …
=> rgw_sal_motr : [CORTX-33020] Improve log levels of SAL layer
